name: Cleanup artifacts

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      expireIn:
        description: 'Expire duration'
        required: true
        default: '1days'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: ${{ github.event.inputs.expireIn }}
